version: '2'
services:
  api:
    build: ./wedding_api
    command: bash -c "gunicorn wedding_api.wsgi -b 0.0.0.0:8000"
#    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wedding_api:/src
  frontend:
    build: ./wedding_frontend
    volumes:
      - './wedding_frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
  backend_proxy:
    image: abiosoft/caddy
    volumes:
      - ./caddy/backend_config:/config
      - ./wedding_api:/docker_django
    environment:
      - API=api # this refers to the service defined at the top of the file
      - BACKEND_PROXY=0.0.0.0:8080
    command: -conf /config/Caddyfile
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./caddy/config:/config
      - ./wedding_api:/docker_django
    ports:
      - "80:80"
    environment:
      - WEB=frontend # this refers to the service defined at the top of the file
      - BACKEND_PROXY=backend_proxy
      - REACT_WEDDING_DOMAIN=0.0.0.0:80
    command: -conf /config/Caddyfile
