version: '2'
services:
  api:
    image: jjorissen/wedding_api:latest
    command: bash -c "sleep 3 && python manage.py migrate && gunicorn wedding_api.wsgi -b 0.0.0.0:8000"
#    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wedding_api:/src
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DEBUG=$DEBUG
#  db:
#    restart: always
#    image: postgres:9.6
#    volumes:
#      - "$HOME/personal/docker_pg/wedding:/var/lib/postgresql/data"
#    environment:
#      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  frontend:
    image: jjorissen/wedding_frontend:latest
    volumes:
      - './wedding_frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
  backend_proxy:
    image: abiosoft/caddy
    volumes:
      - ./caddy/backend_config:/config
      - ./wedding_api:/docker_django
    environment:
      - API=api # this refers to the service defined at the top of the file
      - BACKEND_PROXY=0.0.0.0:8080
    command: -conf /config/Caddyfile
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./caddy/config:/config
      - ./wedding_api:/docker_django
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    environment:

      - WEB=frontend # this refers to the service defined at the top of the file
      - BACKEND_PROXY=backend_proxy
      - REACT_WEDDING_DOMAINS=0.0.0.0:80, 0.0.0.0:9000, 0.0.0.0:9001
      - REACT_WEDDING_DOMAIN=$REACT_WEDDING_DOMAIN
      - REACT_WEDDING_DOMAIN2=$REACT_WEDDING_DOMAIN2
      - REACT_WEDDING_DOMAIN3=$REACT_WEDDING_DOMAIN3
    command: -conf /config/Caddyfile
