version: '2'
services:
  api:
    build: ./wedding_api
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wedding_api:/src
    ports:
      - '8000:8000'
  frontend:
    build: ./wedding_frontend
    volumes:
      - './wedding_frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./caddy/config:/config
      - ./wedding_api:/docker_django
    ports:
      - "80:80"
    environment:
      - WEB=frontend # this refers to the service defined at the top of the file
      - API=api # this refers to the service defined at the top of the file
      - REACT_WEDDING_DOMAIN=0.0.0.0:80
    command: -conf /config/Caddyfile
