# Generated by Django 2.0.5 on 2018-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
