# Generated by Django 2.0.5 on 2018-05-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180520_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, help_text='lower number is higher priority.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=0, help_text='lower number is higher priority.'),
        ),
    ]
